### ISSUE TITLE
YouTube music not working

### ISSUE THREAD

**Issue by Ethanjoyce2010** [ThatGravyBoat/Craftify#102]
Before you say, just download this [https://ytmdesktop.app](url) But that doesn't work; it brings me to [https://github.com/ytmdesktop/ytmdesktop/releases](url), and that is just a 404 page. so i have no clue what to do Now that I know how to get my YouTube cookie, perhaps there is a way to inject my cookies into it?

**Comment by ThatGravyBoat** [comment]
it leads to a 404 because GitHub as a precautionary measure to one of the contributors to the project getting their account hacked GitHub disabled their organization so the maintainers removed that contributors permissions but still require GitHub to restore their organization so you'll just have to wait for GitHub to respond to their support ticket.

**Comment by Ethanjoyce2010** [comment]
Oh, I see. Wrong time, wrong place.
