### ISSUE TITLE
When trying to log into craftify it opens documents folder

### ISSUE THREAD

**Issue by AlbinoFoxGithub** [ThatGravyBoat/Craftify#16]

**Comment by PacBreezy** [comment]
Yup, same with me

**Comment by ThatGravyBoat** [comment]
This is an issue in the library I use for the mod for cross-version stuff so while it gets fixed in that you can just click the link and manually go to this URL to login: https://accounts.spotify.com/authorize?client_id=7314a0ab3c734b2caa4b483032cdd91f&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A21851%2F&scope=user-read-playback-state%20user-modify-playback-state

**Comment by ThatGravyBoat** [comment]
Fixed in new versions
