### ISSUE TITLE
Add Support for Tidal

### ISSUE THREAD

**Issue by 7Kav** [ThatGravyBoat/Craftify#66]
I'm not currently sure if Tidal has an official API or not but im hoping this is possible

**Comment by Mar0xy** [comment]
This should technically be possible by using Tidal-HiFi https://github.com/Mastermindzh/tidal-hifi as it offers an API which can be toggled in its settings


with the following URLs:

`localhost:47836/current`
`localhost:47836/play`
`localhost:47836/pause`
`localhost:47836/playpause`

**Comment by ThatGravyBoat** [comment]
okay so ive looked at and built a small prototype but the problem is that app does not have much info needed and it is hard to work on as it does not support windows fully. 

I can easily get around the windows part but it still doesnt have volume control, shuffle, repeat, info for shuffle, repeat, and volume, artists & times are stored in a manor that is not idle when working with as a string for duration is a little annoying, my work around is parsing them but when I interact with an api I prefer strongly typed stuff.

**Comment by Mar0xy** [comment]
>  but it still doesnt have volume control, shuffle, repeat, info for shuffle, repeat, and volume, artists & times are stored in a manor that is not idle when working with as a string for duration is a little annoying, my work around is parsing them but when I interact with an api I prefer strongly typed stuff.

Wouldn't opening an issue on the repo and asking for this stuff to be added/fixed help in this case?

**Comment by ThatGravyBoat** [comment]
Ive made an issue: https://github.com/Mastermindzh/tidal-hifi/issues/393
