### ISSUE TITLE
Prepare/Update YTMD to use their new V2 API

### ISSUE THREAD

**Issue by Alipoodle** [ThatGravyBoat/Craftify#82]
YTMD Developer here, and wanted to provide a bit of a heads up notice that we're planning on doing a major update to our application.
Including a full rework of the API and Application due to some major security issues in the current build.

Work for V2 is coming near to an end now. 😋 
Releases can be found here: https://github.com/ytmdesktop/ytmdesktop/releases
Full documentation for the current spec of the V2 API can be found here as well: https://github.com/ytmdesktop/ytmdesktop/wiki/v2-%E2%80%90-Companion-Server-API-v1

It was news to me that this uses the YTMD API and I hope to see it continue to work :)

**Comment by ThatGravyBoat** [comment]
I do plan to continue support its just gonna be a little hard due to there not being a socket io api for ktor the library I use for websockets in the library I created to handle all of Craftifys services https://github.com/ThatGravyBoat/jukebox, so I had to originally write my own crude version to support just what was needed for YTMD but now that YTMD uses authentication tokens instead of the old headers I need to figure out how to send those via a raw ws socket.io protocol instead

**Comment by ThatGravyBoat** [comment]
I was looking at the new API the other day due to multiple users already asking for it to be updated to v2 and noticed there was not a volume percent in the player state I was going to report this after I had actually been able to have it run in Craftify but I guess its good time as any to tell you that now.

**Comment by Deemitry88** [comment]
still no update ?

**Comment by ThatGravyBoat** [comment]
still waiting for YTMD to update

**Comment by Tman564wsDEV** [comment]
Can you not use the preview?

**Comment by ThatGravyBoat** [comment]
The preview does not contain all apis needed

**Comment by Tman564wsDEV** [comment]
Oh Ok

**Comment by ThatGravyBoat** [comment]
Added in 1.13.0
